/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Filter } from './filter';
import { QueryConditionItem } from './query-condition-item';
import { Search } from './search';
 /**
 * 分页高级查询输入参数  继承自 BasePageInput，包含高级查询条件列表
 *
 * @export
 * @interface PageAdvancedInput
 */
export interface PageAdvancedInput {

    /**
     * @type {Search}
     * @memberof PageAdvancedInput
     */
    search?: Search;

    /**
     * @type {Filter}
     * @memberof PageAdvancedInput
     */
    filter?: Filter;

    /**
     * 当前页码
     *
     * @type {number}
     * @memberof PageAdvancedInput
     */
    page?: number;

    /**
     * 页码容量
     *
     * @type {number}
     * @memberof PageAdvancedInput
     */
    pageSize?: number;

    /**
     * 排序字段
     *
     * @type {string}
     * @memberof PageAdvancedInput
     */
    field?: string | null;

    /**
     * 排序方向
     *
     * @type {string}
     * @memberof PageAdvancedInput
     */
    order?: string | null;

    /**
     * 降序排序
     *
     * @type {string}
     * @memberof PageAdvancedInput
     */
    descStr?: string | null;

    /**
     * 关键字  用于模糊搜索的关键字，可选
     *
     * @type {string}
     * @memberof PageAdvancedInput
     */
    keyword?: string | null;

    /**
     * 关键字匹配的字段列表  当设置了此字段时，会自动添加关键字模糊匹配条件
     *
     * @type {Array<string>}
     * @memberof PageAdvancedInput
     */
    keywordFields?: Array<string> | null;

    /**
     * 高级查询条件列表  多个条件之间为 AND 关系
     *
     * @type {Array<QueryConditionItem>}
     * @memberof PageAdvancedInput
     */
    conditions?: Array<QueryConditionItem> | null;

    /**
     * 排序字段  要排序的字段名，可选
     *
     * @type {string}
     * @memberof PageAdvancedInput
     */
    orderField?: string | null;

    /**
     * 排序方式  desc：降序，asc：升序，默认降序
     *
     * @type {string}
     * @memberof PageAdvancedInput
     */
    orderType?: string | null;
}
