/* tslint:disable */
/* eslint-disable */
/**
 * Admin.NET 通用权限开发平台
 * 让 .NET 开发更简单、更通用、更流行。整合最新技术，模块插件式开发，前后端分离，开箱即用。<br/><u><b><font color='FF0000'> 👮不得利用本项目从事危害国家安全、扰乱社会秩序、侵犯他人合法权益等法律法规禁止的活动！任何基于本项目二次开发而产生的一切法律纠纷和责任，我们不承担任何责任！</font></b></u>
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { QueryCompareEnum } from './query-compare-enum';
 /**
 * 查询条件项  表示单个查询条件，包含字段名、字段值和比对方式
 *
 * @export
 * @interface QueryConditionItem
 */
export interface QueryConditionItem {

    /**
     * 字段名  要查询的实体属性名称，支持自动识别所属表
     *
     * @type {string}
     * @memberof QueryConditionItem
     */
    field?: string | null;

    /**
     * 查询值  比对的值，支持基本类型、数组（用于 Between 和 In 查询）
     *
     * @type {any}
     * @memberof QueryConditionItem
     */
    value?: any | null;

    /**
     * @type {QueryCompareEnum}
     * @memberof QueryConditionItem
     */
    compare?: QueryCompareEnum;
}
